export interface PatientForm {
  id: string,
  name: string;
  gender: string;
  lastVisit: string;
  age: string;
  birthDate: string;
  address: string;
  cep: string;
  district: string;
  city: string;
  state: string;
  origin: string;
  number: string;
  whatsapp: string;
  instagram: string;
  facebook: string;
  email: string;
  bestCommunicationChannel: string;
  status: string;
  criticity: string;
  speciality: string;
  proceeds: string;
  action: string;
  observations: string;
  financial: string;
  investedValue: string;
  openValue: string;
}
